#!/usr/bin/env bash

trap 'unset ERR CHECK TMPFILE Readable' EXIT SIGINT SIGKILL SIGTERM

#-----------------------------------------------------------Check some errors

ERR(){
	printf '%s\n' "doasedit: $2" && exit $1
}

[ $UID -eq 0 ] && ERR 2 'denied to run as root...'

[ -z "$1" ] && ERR 2 "doesn't has file to edit..."

[ -n "$2" ] && ERR 2 'only able to edit one file...'

[ -f "$1" ] || ERR 2 "$1 is a directory or doesn't exists..."

[ -O "$1" ] && ERR 2 "$1 doesn't need root access..."

if [ -r "$1" ]; then
	Readable=1
else
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF

		doasedit() doesn't has permission to read $1
		if continue you will need to type your password 3 times
		unless you have \`persist\` option in your /etc/doas.conf

	EOF

	read -p 'Do you want to continue? [y/N]: '
	case "$REPLY" in
		[Nn][Oo]|[Nn]|'')
			exit 1 ;;

		[Yy][Ee][Ss]|[Yy])
			Readable=0 ;;

		*)
			ERR 2 "unknown answer(s) $1..." ;;
	esac
fi

[ -w "$1" ] && ERR 2 "$1 doesn't need root access..."

#-----------------------------------------------------------Prepare and Set variables

# Make Random Variables Static
TMPFILE="${TMPDIR:-/tmp}/doasedit-$SRANDOM"

# Copy Original File to Tmp Directory
[ "$Readable" -eq 1 ] && cp $1 $TMPFILE || doas -- cp $1 $TMPFILE

[ "$Readable" -eq 0 ] && doas -- chown $USER $TMPFILE

#----------------------------------------------------------Start to edit the file

# Edit tmp file
${DOAS_EDITOR:-vi} $TMPFILE ||
	ERR 1 '$DOAS_EDITOR is set to something that unusable...'

# Doesn't do Anything If File's Content Doesn't Change
cmp -s $1 $TMPFILE && rm -f $TMPFILE &&
	ERR 0 "$1 doesn't change..."

while :; do

	# Ask user to create a backup, yes by default
	read -p "doasedit: do you want to create a backup of $1 [Y/n]: "

    case "$REPLY" in

		[Yy][Ee][Ss]|[Yy]|'')
			doas -- cp -b $TMPFILE $1

			# Break while loop only when user successfully type password
			[ $? -eq 0 ] &&
				printf '%s\n' "doasedit: backup at ${1}~..." &&
				break ;;

		[Nn][Oo]|[Nn])
			doas -- cp $TMPFILE $1

			# Break while loop only when user successfully type password
			[ $? -eq 0 ] && break ;;

		*)
			printf 'doasedit: invaild answer(s)...\n' ;;
    esac

done

rm -f $TMPFILE
