#!/usr/bin/env bash

#-----------------------------------------------------------Check some errors

ERR(){
	printf '%s\n' "doasedit: $2" && exit $1
}

[ $UID = 0 ] && ERR 1 'denied to run as root...'

[ -z "$1" ] && ERR 1 "doesn't has file to edit..."

[ -n "$2" ] && ERR 1 'only able to edit one file...'

[ ! -f "$1" ] && ERR 1 "$1 is a directory or doesn't exist..."

[ ! -r "$1" ] && ERR 1 "doesn't has permission to read $1..."

[ -w "$1" -o -O "$1" ] && ERR 1 "$1 doesn't need root access..."

#-----------------------------------------------------------Prepare and Set variables

# Make Random Variables Static
TmpFile="${TMPDIR:-/tmp}/doasedit-$SRANDOM"

# Copy Original File to Tmp Directory
\cp $1 $TmpFile

#----------------------------------------------------------Start to edit the file

# Edit tmp file
${EDITOR:-vi} $TmpFile

# Doesn't do Anything If File's Content Doesn't Change
cmp $1 $TmpFile -s && rm -f $TmpFile && ERR 0 "$1 doesn't change..."

while :; do

	# Ask user to create a backup, Yes by default
	read -p "doasedit: do you want to create a backup of $1 [Y/n]: "

    case $REPLY in

		[Yy][Ee][Ss]|[Yy]|'')
			doas cp -b $TmpFile $1

			# Break while loop only when user successfully type password
			[ "$?" = 0 ] && printf "doasedit: backup at ${1}~...\n" && break ;;

		[Nn][Oo]|[Nn])
			doas cp $TmpFile $1

			# Break while loop only when user successfully type password
			[ "$?" = 0 ] && break ;;

		*)
			printf 'doasedit: invaild answer(s)...\n' ;;
    esac

done

rm -f $TmpFile

unset ERR TmpFile
