#!/bin/sh

#-----------------------------------------------------------Check some Errors

Err() {
	printf '%s\n' "doasedit: $2" 1>&2
	test $1 -gt 0 && exit $1
}

test `id -u` -eq 0 && Err 2 'denied to run as root...'

test $# -ne 1 && Err 2 "no file was specify..."

test -f "$1" || Err 2 "'$1' is a directory or doesn't exists..."

test -O "$1" -o -w "$1" && Err 2 "'$1' doesn't need root access..."

if test -r "$1"; then
	Readable=1
else
	while read -r Curline; do
		printf '%b\n' "$Curline"
	done <<-EOF

		\rdoasedit() doesn't has permission to read '$1'
		\rif continue, you'll need to type password 3 times
		\runless you have 'persist' option in '/etc/doas.conf'

	EOF

	read -p 'Do you want to continue? [y/N]: ' Answer
	case "$Answer" in
		[Nn][Oo]|[Nn]|'')
			exit 1 ;;

		[Yy][Ee][Ss]|[Yy])
			Readable=0 ;;

		*)
			Err 2 "unknown answer(s) '$1'..." ;;
	esac
fi

#-----------------------------------------------------------Prepare and Set variables

# Make random variables static
TMPFILE="${TMPDIR:-/tmp}/doasedit-$SRANDOM"

# Copy original file to temp directory
if test $Readable -eq 1; then
	cp "$1" "$TMPFILE"
else
	while :; do doas cp "$1" "$TMPFILE" && break; done
	while :; do doas chown "$USER" "$TMPFILE" && break; done
fi

# Remove temp file when exit
trap 'rm -f "$TMPFILE"' EXIT

test -w "$TMPFILE" || Err 2 "'$1' is write protected, aborted..."

#----------------------------------------------------------Start to edit the file

# Edit temp file
${DOAS_EDITOR:-vi} "$TMPFILE" ||
	Err 2 '$DOAS_EDITOR is set to something that unusable...'

# Don't do anything if file's content doesn't change
cmp -s "$1" "$TMPFILE" && Err 1 "'$1' doesn't change..."

while :; do
	# Break while loop only when user successfully type password
	doas cp "$TMPFILE" "$1" && break
done
