#!/usr/bin/env bash

#-----------------------------------------------------------Check some Errors

Program="${0##*/}"

Err() {
	printf '%s\n' "$Program: $2" 1>&2
	(( $1 > 0 )) && exit $1
}

if ! type -P doas &>/dev/null; then
	Err 1 'dependency, `doas`, not met...'
fi

((UID)) || Err 2 'denied to run as root...'

(( $# == 1 )) || Err 2 'no file was given...'

[[ -f $1 ]] || Err 2 "$1: not a file..."

[[ -O $1 || -w $1 ]] && Err 2 "needn't root access..."

if [[ -r $1 ]]; then
	Readable=1
else
	read -d '' <<-EOF

		$Program(1) doesn't has permission to read '$1'.
		If continue, you'll need to type password 3 times.
		Unless you've 'persist' option in doas.conf(5).

	EOF

	printf '%s' "$REPLY"

	read -p 'Do you want to continue? [y/N]: '
	case "${REPLY,,}" in
		no|n|'')
			exit 1 ;;

		yes|y)
			Readable=0 ;;

		*)
			Err 2 "$REPLY: invaild reply..." ;;
	esac
fi

#-----------------------------------------------------------Prepare and Set Variables

# Make random variable static.
TMPFILE="${TMPDIR:-/tmp}/doasedit-$(( $SRANDOM * $$ ))"

# Copy original file to temp directory.
if (( Readable == 1 )); then
	cp -- "$1" "$TMPFILE"
else
	while :; do
		doas -- cp -- "$1" "$TMPFILE" && break
	done

	while :; do
		doas -- chown -- $UID "$TMPFILE" && break
	done
fi

# Remove the temp file when exit.
trap "rm -f -- $TMPFILE" EXIT

[[ -w $TMPFILE ]] || Err 1 "$1: is write protected, aborted..."

#----------------------------------------------------------Start to Edit the File

EDITOR="${EDITOR:-vi}"

# Edit the temp file.
if ! $EDITOR "$TMPFILE"; then
	Err 1 "unable to use \`$EDITOR\` as an editor..."
fi

while :; do
	# Break while loop only when user successfully type password.
	doas -- cp -- "$TMPFILE" "$1" && break
done
