#!/usr/bin/env bash

readonly progrm=${0##*/}

eprintf() { printf "$@" 1>&2; }

panic() {
	eprintf '%s\n' "$progrm: $2"
	(( $1 )) && exit $1
}

if ! type -P doas &>/dev/null; then
	panic 1 'dependency, `doas`, not met...'
fi

((UID)) || panic 1 'denied to run as root...'

(( $# == 1 )) || panic 1 'no files were given...'

[[ -f $1 ]] || panic 1 "$1: not a file..."

[[ -O $1 || -w $1 ]] && panic 1 "needn't root access..."

readonly temp_file=${TMPDIR:-/tmp}/doasedit-$SRANDOM

if [[ -r $1 ]]; then
	cp -a -- "$1" "$temp_file"
else
	while :; do
		doas cp -a -- "$1" "$temp_file" && break
	done

	while :; do
		doas chown -- $UID "$temp_file" && break
	done
fi

trap "rm -f -- \"$temp_file\"; sync" EXIT

[[ -w $temp_file ]] || panic 1 "$1: is write protected, aborted..."

[[ $EDITOR ]] || declare -xr EDITOR=vi

if ! "${EDITOR[@]}" "$temp_file"; then
	panic 1 "unable to use \`$EDITOR\` as an editor..."
fi

while :; do
	doas cp -a -- "$temp_file" "$1" && break
done
